[project]
name = "ai-researcher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain>=1.2.7",
    "langchain-core>=1.2.7",
    "pypdf2>=3.0.1",
    "requests>=2.32.5",
]
